With change from matplotlib 3.6 to matplotlib 3.7 there appear an error "line 1177, in _blit_draw cur_view = ax._get_view() AttributeError: 'NoneType' object has no attribute '_get_view'". This disappears when I deleted         # Delete all elements of the Figure         AxCart.clear()         AxSlider.clear()
the change has no visible effect on GUI neither with old nor with new version of matplotlib. However deleting .clear() in BruntonTest has the effect on plotting and .clear() does not cause the crash there.